version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: clothes_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clothes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
